version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - npm run build:deploy -- --prod
artifacts:
  files:
    - '**/*'
  base-directory: www
